name: elephant-doc
dependencies:
- python=3.6
- ipython
- jupyter
- docutils
- numpydoc
- six=1.12.0
- sphinx_rtd_theme
- pip:
  - neo==0.7.1
  - quantities==0.12.3
  - sphinx_bootstrap_theme
  - nbsphinx
  - matplotlib
  - tables
  - h5py

